### ISSUE TITLE
after update to Revision 34: Error getting options. Please run --configure.

### ISSUE THREAD

**Issue by schaefer-dev** [BasioMeusPuga/twitchy#1]
Above error is being thrown even when running `twitchy --configure`. Everything worked perfectly on the earlier version (not sure which one)

Edit: from Rev 25

**Comment by BasioMeusPuga** [comment]
Growing pains, I'm afraid. 
I implemented the notification function in Rev 30, and the script was looking for the check interval setting.

I've redone `--configure` in Rev 35, so everything should be working now.

**Comment by schaefer-dev** [comment]
that fixed the error mentioned above! Got a new one now after the config process

Edit: Replaces Stream name with StreamName1 as example, the error is being thrown on a stream which was (after using the account sync) in my list twice using different capitalization, so I manually deleted the one which is throwing this error right now

`Checking channels...
Traceback (most recent call last):
  File "/Users/daniel/dotfiles/scripts/twitchy.py", line 1006, in <module>
    main()
  File "/Users/daniel/dotfiles/scripts/twitchy.py", line 1003, in main
    watch("BlankForAllIntensivePurposes")
  File "/Users/daniel/dotfiles/scripts/twitchy.py", line 623, in watch
    get_status(status_check_required)
  File "/Users/daniel/dotfiles/scripts/twitchy.py", line 602, in get_status
    alt_name = altname_list[status_check_required.index(channel_name)]
ValueError: 'streamName1' is not in list`

**Comment by schaefer-dev** [comment]
I can "workaround" the error by adding the (previously deleted) stream-duplicate using the different capitalisation again.

Is there a easy way for me to just reset the database?

**Comment by schaefer-dev** [comment]
You can reliably cause this error by adding a stream twice using different capitalisation and deleting one of them afterwards.

The next call of `twitchy` will show the same error

**Comment by BasioMeusPuga** [comment]
I've been relying on Twitch to give me non-redundant data, so I've basically let go of sanity checking for the sake of MOAR SPEED.

In case you don't care about the statistics in the db, it's as simple as: `rm ~/.twitchy.db`

**Comment by schaefer-dev** [comment]
Speed is always the most important thing! But its probably a easy solution to just transform all the user input into lowercase which should avoid all these problems

Haven't watched at your code at all! Just the first thing that came to my mind

Thanks a lot for coming up with a fix so quickly!

**Comment by BasioMeusPuga** [comment]
...and done. It's in master now. All lowercase, all the time.

And yes, if anything, I'm grateful for the bug report. :)
