### ISSUE TITLE
Twitchy cant play any streams, it just aborts without any feedback

### ISSUE THREAD

**Issue by Hund** [BasioMeusPuga/twitchy#11]
```
$ twitchy
 Checking 39 channel(s)...

 ChannelName           Uptime       StreamStatus                                                                                    
 1 rendogtv               40m     MINECRAFT | BRAND NEW SURVIVAL SERVER!!! || RENDOG
 2 Soaryn                 35m     Boop | Free Sub: !prime | Twitter: @Soaryn117
 Channel number(s)? 2
 q / Ctrl + C to quit 
 Now watching:
 Soaryn | Source
 Soaryn: 8s (4) | Minecraft: 24s (2)
$
```

I'm not sure how to debug this? It works if I open the stream directly with Streamlink though.

**Comment by BasioMeusPuga** [comment]
I'm unable to reproduce it here. Even with `soaryn`
I assume you're on the latest revision and everything. If that is the case, could you please move/delete ~/.config/twitchy/twitchy.db and check again?

**Comment by Hund** [comment]
Yes, I forgot to mentioned that. I also tried starting fresh, by renaming the folder. :/

**Comment by BasioMeusPuga** [comment]
How are you adding channels after starting afresh? If it's a sync from your account, could you please upload a copy of your twitchy.db?

**Comment by Hund** [comment]
Syncing them from my Twitch-account. 

[twitchy.zip](https://github.com/BasioMeusPuga/twitchy/files/1272814/twitchy.zip)

(I had to put it in a ZIP-archive to be able to upload it here.)

**Comment by BasioMeusPuga** [comment]
I'm afraid I still can't replicate this. There's nothing in the strings in the database that might trip up the script. As far as I can tell, the entries in the database mean that the name of the channel is getting passed to livestreamer.

Could you apply this patch and tell me if you get an error?

https://pastebin.com/ecgd3GLp

**Comment by Hund** [comment]
Tried the patch and it didn't say anything. :/

**Comment by BasioMeusPuga** [comment]
This is weird.
You're on Arch, right? Let's start with the assumption than an update borked something.
If it's happening on all your systems, despite a restart and a reinstall, try checking if you're using `streamlink` instead of `livestreamer`. The latter is effectively deprecated.
If it still doesn't work, I'll send a patch that does nothing but output debug strings.

**Comment by Hund** [comment]
Nope, I'm on Gentoo. I always forget to add essential information.  :/ I've checked the log for emerge, but there's a lot of stuff there and I'm not really sure when it started.

I tested Twitchy on Arch and it seems to be working just fine there still.

**Comment by BasioMeusPuga** [comment]
I'm afraid this puts us in "non standard user configuration" territory.
I'd recommend starting with a recompile of (at least) streamlink, python 3.6, and mpv (turn off hardware acceleration).

Best of luck.

**Comment by Hund** [comment]
Hey, good recomendation. It works when I set the option `MPVHardwareAcceleration` to `false`. Now I just need to figure out why that stopped working. Thanks!

**Comment by apetresc** [comment]
It looks like I can reproduce this issue exactly - everything works fine with VLC or with MPV _without_ hardware acceleration, but as soon as I set it to MPV with `MPVHardwareAcceleration = True`, it crashes without any logging at all.

I'm on Arch, NVidia proprietary driver, and MPV works fine normally with hardware acceleration.

Mind passing me that debug build? I can try it and pass you the results.

**Comment by BasioMeusPuga** [comment]
This is, unfortunately, expected behavior. `vaapi` is only for Intel hardware. For Nvidia cards, you're expected to use `vdpau`. 
I've put in an option for that in the latest revision. You will need to delete your config file and start again.

I've also decided to start catching ALL errors for the streamlink process, but I'm afraid mpv doesn't generate any when selecting `vdpau`.

Tell me if anything changes.

**Comment by Hund** [comment]
Nice to see support for vdpau. I went from 50% to 5% CPU usage. :) Now I just have to write a patch for the colors.

**Comment by apetresc** [comment]
Yup, I can confirm that `vdpau` works with `mpv` and doesn't crash anymore - and `nvidia-smi` confirms that acceleration is working :) Thanks for the super-speedy resolution!
