### ISSUE TITLE
`twitchy -w` stopped accepting upper-case characters

### ISSUE THREAD

**Issue by apetresc** [BasioMeusPuga/twitchy#19]
I suspect the underlying cause here is a Twitch API change because I'm quite certain it used to work fine on the same git rev, but basically `twitchy -w` no longer accepts upper-case characters, ***even when the channel name is supposed to have them***.

Case in point:
```
$ twitchy -w Chess
 No valid channels.
$ twitchy -w chess
 Checking 1 channel(s)...
 Chess
 1 Chess                  1,004       2018 PRO Chess League, Week 2
 Number? ^C
```

The channel in question is _supposed_ to be `Chess`, not `chess`, and that's what twitchy's own output is returning.

**Comment by BasioMeusPuga** [comment]
This is fixed now. In that I added a line somewhere and shook my fist at the sky.
