### ISSUE TITLE
Invalid value of 'args_to_subprocess' causes player to close

### ISSUE THREAD

**Issue by schaefer-dev** [BasioMeusPuga/twitchy#2]
Found another one :)

executing `twitchy` followed by e.g. `3` never starts the stream (ends after ~30s).

The executed query (args_to_subprocess) for me contains exactly this string: 

> livestreamer twitch.tv/'rush' 'source' --player 'mpv --hwdec=vaapi --vo=vaapi --cache 8192 --title Rush' --hls-segment-threads 3

something is going wrong here!

Edit: the problem is caused by the hw-acc. Disabling that part in mpv solves the problem, although I am not sure why hw-acc is causing an Issue

Edit2: I'm using a 2015 13" rMBP 10.11.6 with the following MPV:

> mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
>  built on Fri Aug 26 23:02:21 BST 2016
> ffmpeg library versions:
>    libavutil       55.28.100
>    libavcodec      57.48.101
>    libavformat     57.41.100
>    libswscale      4.1.100
>    libavfilter     6.47.100
>    libswresample   2.1.100
> ffmpeg version: 3.1.3

just in case thats relevant for the hw-acc problem

**Comment by BasioMeusPuga** [comment]
I'm not sure either. My internet is currently in the process of foaming at the mouth so I'll have to wait to see if this issue is due to the way `shlex` is parsing the string, or if something is the matter with mpv. 

I'll update this soon.

**Comment by BasioMeusPuga** [comment]
So I went through every combination of mpv / hw acceleration / quality setting I could, and I can't seem to reproduce the error. The livestreamer query pasted above also works as-is in a terminal.

If no streams are working with hw-accel, I'd say this is an issue with vaapi support in your installation of mpv/gstreamer.

**Comment by BasioMeusPuga** [comment]
So yes, the issue is with vaapi. Apparently it only supports X11. The obvious workaround is disabling hw-accel for now; but I'll see if I can put in relevant sane defaults for OSX in a future revision.
