### ISSUE TITLE
CommaError: possible unparseable string in non-interactive

### ISSUE THREAD

**Issue by lasers** [BasioMeusPuga/twitchy#20]
Hi. I saw something in the code. It is possible to split fields incorrectly with `,` when using `non-interactive` because some (alt) fields can have their own `,` too.

**Comment by BasioMeusPuga** [comment]
Absolutely. I remember thinking about this a while back, but I never got around to fixing it. It should be fixed now, though.

Either delete your ~/.config/twitchy3/twitchy.cfg or add something like the following to the last line:

`Delimiter = <special character>`

It bears mention that if you're using one of the plugins, you'll need to change the Delimiter there as well.

**Comment by lasers** [comment]
Works okay now in latest master / fixed via commit dad9561. Many thanks. :-)
