### ISSUE TITLE
twitchy crahes if streamer doesnt define a game

### ISSUE THREAD

**Issue by jasondaigo** [BasioMeusPuga/twitchy#22]
im sorry if this is already known but if not i want to tell you that if the streamer doesnt define a game he streams twitchy fails to load with the following warning:
`[jason@whitepearl ~]$ twitchy `
` Checking 45 channel(s)...`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.6/site-packages/twitchy/twitchy_api.py", line 268, in get_game`
`    'EQUALS')[0]`
`TypeError: 'NoneType' object is not subscriptable`
` `
`During handling of the above exception, another exception occurred:`
` `
`Traceback (most recent call last):`
`  File "/usr/bin/twitchy", line 11, in <module>`
`    load_entry_point('twitchy==3.2.0', 'console_scripts', 'twitchy')()`
`  File "/usr/lib/python3.6/site-packages/twitchy/__main__.py", line 400, in main`
`    watch_channel(None)`
`  File "/usr/lib/python3.6/site-packages/twitchy/__main__.py", line 194, in watch_channel`
`    id_string_list).check_channels()`
`  File "/usr/lib/python3.6/site-packages/twitchy/twitchy_api.py", line 365, in check_channels`
`    game_data = self.get_game(game_id)`
`  File "/usr/lib/python3.6/site-packages/twitchy/twitchy_api.py", line 278, in get_game`
`    game_name = game_details[0][1].replace("'", "")`
`IndexError: list index out of range`

its not happenig every day that a streamer doesnt set the game he plays but i would say once a week

**Comment by BasioMeusPuga** [comment]
Hey. Thanks for the traceback. It should be fixed now.
