### ISSUE TITLE
twitchy doesn't respect player config option

### ISSUE THREAD

**Issue by thepixelmonk** [BasioMeusPuga/twitchy#23]
twitchy didn't seem to respect the player config option and just used mpv no matter what I specified.

In `twitchy_config.py`, changing:

```
if player == 'mpv' and hw_accel != 'false':
    player_final = 'mpv --hwdec={0} --cache 8192'.format(hw_accel)
else:
    player_final = 'mpv --cache 8192'
```

to

```
if player == 'mpv' and hw_accel != 'false':
    player_final = 'mpv --hwdec={0} --cache 8192'.format(hw_accel)
else:
    player_final = player
```

fixed my issue. I also had to remove the `--title` parameter in `twitchy_play.py` since it's not a valid mplayer parameter.

**Comment by BasioMeusPuga** [comment]
Yeah. This was totally borked. I've fixed it in the latest commit. Thanks for the report.
