### ISSUE TITLE
[Feature Request]: Option to launch stream in its own instance

### ISSUE THREAD

**Issue by mattyrc** [BasioMeusPuga/twitchy#25]
It would be nice if there was an option to launch the stream in its own instance so that the stream could continue to run in mpv when I exit out of twitchy. Currently I am using twitchy to see who is online, and then using streamlink to manually launch the stream with 'disown' to keep the terminal free.

Also just want to say thanks for twitchy. I've tried many different cli twitch apps and this is my favorite.

**Comment by BasioMeusPuga** [comment]
You're welcome.

I've added a `--hanselgretel` flag. That'll take care of the children. It will disable time tracking though.

**Comment by mattyrc** [comment]
Wow, that was fast!

The new flag is working great. Thank you!
