### ISSUE TITLE
Detect and display hosting?

### ISSUE THREAD

**Issue by jedahan** [BasioMeusPuga/twitchy#26]
It would be cool if a streamer is hosting someone else, that you could see and choose the hosted stream

**Comment by BasioMeusPuga** [comment]
I'm not entirely sure the New Twitch API supports that at the moment. If that changes, I'll definitely look into it.

**Comment by jedahan** [comment]
`http://tmi.twitch.tv/hosts?include_logins=1&host={id}` I think is the endpoint, where id is the id of who might be hosting.

**Comment by BasioMeusPuga** [comment]
I've seen that. I'm using the official Twitch API with the helix endpoints. I'm afraid "unsupported, undocumented, and subject to change at any time" doesn't really work for maintenance purposes.
