### ISSUE TITLE
Twitchy does not work anymore

### ISSUE THREAD

**Issue by irowea** [BasioMeusPuga/twitchy#33]
Hello @BasioMeusPuga !

First of all thank you very much for making twitchy, I have been using it extensively for quite sometime and it is great.

Unfortunately the last couple of days twichy does not seem to work properly. I am not sure if it has anything to do with the latest streamlink and mpv [changes](https://github.com/streamlink/streamlink/issues/2764) but altough searching, subscribing etc works playing the stream does not.

From what I checked there are no ways to activate a debug flag and there are no errors since twitchy fails quietly. I am on Arch Linux using mpv 0.32 and streamlink 1.3.1

Any idea what might be wrong?

Edit1: I tried changing the flags to use the new format and it works!!!

> - change behavior when using legacy option syntax with options that start
      with two dashes (``--`` instead of a ``-``). Now, using the recommended
      syntax is required for options starting with ``--``, which means an option
      value must be strictly passed after a ``=``, instead of as separate
      argument. For example, ``--log-file f.txt`` was previously accepted and
      behaved like ``--log-file=f.txt``, but now causes an error. Use of legacy
      syntax that is still supported now prints a deprecation warning.

plus 

> The documented MPV cache parameter was changed in MPV's 0.30.0 release not too long ago
--cache parameter only accept yes, no and auto.

In order to fix it you basically need to change all mpv arguments to use the new --argname= format and --cache= either yes no or auto currently using a number 8192

```
diff --git a/twitchy/twitchy_config.py b/twitchy/twitchy_config.py
index 7f55408..23f0671 100644
--- a/twitchy/twitchy_config.py
+++ b/twitchy/twitchy_config.py
@@ -231,9 +231,9 @@ class Options:
         player_final = player
         if player == 'mpv':
             if hw_accel != 'false':
-                player_final = 'mpv --hwdec={0} --cache 8192'.format(hw_accel)
+                player_final = 'mpv --hwdec={0} --cache=auto'.format(hw_accel)
             else:
-                player_final = 'mpv --cache 8192'
+                player_final = 'mpv --cache=auto'
 
         default_quality = video_section.get('DefaultQuality', 'high')
         if default_quality not in ['low', 'medium', 'high', 'source']:
diff --git a/twitchy/twitchy_play.py b/twitchy/twitchy_play.py
index 2d1ead3..b4d51a1 100644
--- a/twitchy/twitchy_play.py
+++ b/twitchy/twitchy_play.py
@@ -44,7 +44,7 @@ class Playtime:
         display_name = self.channel_params['display_name']
         player = Options.video.player_final
         if player[:3] == 'mpv':
-            player += f' --title {display_name}'
+            player += f' --title={display_name}'
         quality = Options.quality_map[self.channel_params['quality']]
 
         # The following prints to the console
```

Edit2: Playing VODs still fails :(

Edit3: Fixed there was another argument usage in the VOD class

```
@@ -148,7 +148,7 @@ class VOD:
         self.player_process = None
 
     def play(self):
-        player = Options.video.player_final + f' --title {self.display_name}'
+        player = Options.video.player_final + f' --title={self.display_name}'
         args_to_subprocess = (
             f"streamlink {self.vod_url} best --player '{player}'")
         hls_settings = ' --hls-segment-threads 3 --player-passthrough=hls'
```

The streams take a while to start so that might have to do with the cache argument I set it to auto for the tests but I guess better to look into it a bit more.

If you do not have time to do the fixes I can do a PR so let me know :+1:

**Comment by BasioMeusPuga** [comment]
Hey. Thanks for the bug report and doing the work tracking this down. I hadn't updated my system in a bit so I was still running on an older `mpv`. I've made the fixes and everything seems to be working. I'll play around with the `cache` argument a little myself.
